---
title: Addition of Emphysema-CNN score improves upon prescreening risk calculated
  by LCRAT
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load packages

```{r load-packages, results='hide', message=FALSE}
# List packages to be loaded (and installed if needed)
packages <-
    c(
        "readr",
        "here",
        "dplyr",
        "psych",
        "pROC"
    )

# List packages that are not installed
not_installed <-
    packages[!(packages %in% installed.packages()[, "Package"])]

# Install packages that are not installed
  if (length(not_installed))
    install.packages(not_installed)

# Load all packages
lapply(packages, require, character.only = TRUE)

```

## Merge in Wes' T0 data

```{r merge-data, results='hide', message=FALSE}
t0_nlst_emp <- read_csv(here('data/T0_data.csv'))
t1_nlst_emp <- read_csv(here('data/T1_data.csv'))
t2_nlst_emp <- read_csv(here('data/T2_data.csv'))
data_screen_abn_neg <- readRDS(here('data/data_screen_abn_neg.rds'))
data_screen_abn_neg_emp_t0 <-
    merge(data_screen_abn_neg, t0_nlst_emp, by = "pid")
data_screen_abn_neg_emp_t1 <-
    merge(data_screen_abn_neg, t1_nlst_emp, by = "pid")
data_screen_abn_neg_emp_t2 <-
    merge(data_screen_abn_neg, t2_nlst_emp, by = "pid")
```

## Fit models

### T0: Without physician-annotated features

```{r score-only-t0}
# Prescreening risk only
glm_screen_neg_t0 <-
    glm(case ~ log1yrisk - 1,
        data = data_screen_abn_neg_emp_t0,
        family = binomial(link = 'log'))
summary(glm_screen_neg_t0)
predictions <- predict(glm_screen_neg_t0, type = "response")
pROC::auc(data_screen_abn_neg_emp_t0$case, predictions)

# Prescreening risk + p_emph
glm_screen_neg_pemph_t0 <-
    glm(case ~ log1yrisk + p_emph - 1,
        data = data_screen_abn_neg_emp_t0,
        family = binomial(link = 'log'),
        na.action = na.exclude)
summary(glm_screen_neg_pemph_t0)
predictions <- predict(glm_screen_neg_pemph_t0, type = "response")
pROC::auc(data_screen_abn_neg_emp_t0$case, predictions)

# Prescreening risk + logit p_emph
glm_screen_neg_logitpemph_t0 <-
    glm(case ~ log1yrisk + I(logit(p_emph)) - 1,
        data = data_screen_abn_neg_emp_t0,
        family = binomial(link = 'log'),
        na.action = na.exclude)
summary(glm_screen_neg_logitpemph_t0)
predictions <- predict(glm_screen_neg_logitpemph_t0, type = "response")
pROC::auc(data_screen_abn_neg_emp_t0$case, predictions)

# Prescreening risk + log p_emph
glm_screen_neg_logpemph_t0 <-
    glm(case ~ log1yrisk + I(log(p_emph)) - 1,
        data = data_screen_abn_neg_emp_t0,
        family = binomial(link = 'log'),
        na.action = na.exclude)
summary(glm_screen_neg_logpemph_t0)
predictions <- predict(glm_screen_neg_logpemph_t0, type = "response")
pROC::auc(data_screen_abn_neg_emp_t0$case, predictions)
```

### T0: With physician-annotated features

```{r score-phys-t0}
glm_screen_neg_cons_t0 <-
    glm(
        case ~ log1yrisk + log1yrisk:consolidation - 1,
        data = data_screen_abn_neg_emp_t0,
        family = binomial(link = 'log'),
        na.action = na.exclude
    )
summary(glm_screen_neg_cons_t0)
predictions <- predict(glm_screen_neg_cons_t0, type = "response")
pROC::auc(data_screen_abn_neg_emp_t0$case, predictions)

glm_screen_neg_emph_t0 <-
    glm(
        case ~ log1yrisk + log1yrisk:emphysema - 1,
        data = data_screen_abn_neg_emp_t0,
        family = binomial(link = 'log'),
        na.action = na.exclude
    )
summary(glm_screen_neg_emph_t0)
predictions <- predict(glm_screen_neg_emph_t0, type = "response")
pROC::auc(data_screen_abn_neg_emp_t0$case, predictions)

glm_screen_neg_cons_emph_t0 <-
    glm(
        case ~ log1yrisk + log1yrisk:consolidation + log1yrisk:emphysema - 1,
        data = data_screen_abn_neg_emp_t0,
        family = binomial(link = 'log'),
        na.action = na.exclude
    )
summary(glm_screen_neg_cons_emph_t0)
predictions <- predict(glm_screen_neg_cons_emph_t0, type = "response")
pROC::auc(data_screen_abn_neg_emp_t0$case, predictions)

glm_screen_neg_cons_emph_pemph_t0 <-
    glm(
        case ~ log1yrisk + log1yrisk:consolidation + log1yrisk:emphysema + I(log(p_emph)) - 1,
        data = data_screen_abn_neg_emp_t0,
        family = binomial(link = 'log'),
        na.action = na.exclude
    )
summary(glm_screen_neg_cons_emph_pemph_t0)
predictions <- predict(glm_screen_neg_cons_emph_pemph_t0, type = "response")
pROC::auc(data_screen_abn_neg_emp_t0$case, predictions)
```


### Final summary

```{r final-summary}
anova(glm_screen_neg_cons_t0, glm_screen_neg_cons_emph_t0, glm_screen_neg_cons_emph_pemph_t0)
```
